name: Hello world1

on:
    push:
        branches:
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello step
              run: echo "Hello world"